// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"github.com/makesalekz/gateway/internal/clients"
	"github.com/makesalekz/gateway/internal/conf"
	"github.com/makesalekz/gateway/internal/handlers"
	"github.com/makesalekz/gateway/internal/router"
	"github.com/makesalekz/gateway/internal/server"
)

func wireApp(bc *conf.Bootstrap, logger log.Logger, openapiSpec []byte) (*kratos.App, func(), error) {
	iamClient := clients.NewIAMClient()
	productsClient := clients.NewProductsClient()
	salesClient := clients.NewSalesClient()
	warehouseClient := clients.NewWarehouseClient()
	ordersClient := clients.NewOrdersClient()
	agentsClient := clients.NewAgentsClient()
	storesClient := clients.NewStoresClient()
	billingClient := clients.NewBillingClient()

	authHandler := handlers.NewAuthHandler(iamClient)
	productsHandler := handlers.NewProductsHandler(productsClient)
	salesHandler := handlers.NewSalesHandler(salesClient)
	dashboardHandler := handlers.NewDashboardHandler(salesClient, warehouseClient, storesClient, billingClient)
	agentsHandler := handlers.NewAgentsHandler(agentsClient, ordersClient)
	docsHandler := handlers.NewDocsHandler(openapiSpec)

	muxRouter := router.New(authHandler, productsHandler, salesHandler, dashboardHandler, agentsHandler, docsHandler)
	httpServer := server.NewHTTPServer(bc, muxRouter)

	app := newApp(logger, httpServer)

	cleanup := func() {}

	return app, cleanup, nil
}
